name         = "auth0_client_secret"
display_name = "Auth0 Client Secret"
description  = "A long secret value used to encrypt the session cookie."
default      = "dne"

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-client-secret"

user_configurable = true
