name          = "auth0_secret"
display_name  = "Auth0 Secret"
description   = "Auth0 Client Secret for BYOC Nuon - app.{{.nuon.id}}.nuon.run"
auto_generate = true

kubernetes_sync             = true
kubernetes_secret_namespace = "dashboard-ui"
kubernetes_secret_name      = "dashboard-ui-auth0-secret"

user_configurable = false
