name         = "nuon_auth_allow_all_users"
description  = "If this is set to true, any user with an email in one of the allowed_domains will be able to register."
default      = ""
display_name = "Allow All Users"
required     = true
group        = "oidc"
type         = "bool"

user_configurable = false
