name         = "nuon_dns_domain"
description  = "The domain under which Route53 zones will be provisioned for installs, when using the nuon_dns feature."
display_name = "Install DNS Delegation Domain"
required     = true
group        = "dns"

user_configurable = false
