name         = "root_domain"
description  = "The root domain. Services will be made available at subdomains of this root domain."
display_name = "Root Domain"
required     = true
group        = "dns"

user_configurable = true
