name         = "auth_audience"
description  = "Auth0 Audience"
default      = "api.{{.nuon.install.id}}.nuon.run"
display_name = "Auth0 Audience"
required     = false
group        = "auth"

user_configurable = true
