name         = "nuon_auth_client_id"
description  = "OIDC Client ID from your identity provider."
default      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
display_name = "Auth Client ID"
required     = true
group        = "auth"

user_configurable = true
