name         = "github_app_client_id"
description  = "The github app client id."
default      = ""
display_name = "GitHub App Client ID"
group        = "github"
required     = true

user_configurable = true
