name         = "nuon_auth_client_secret"
display_name = "Auth Client Secret"
description  = "OIDC Client Secret from your identity provider."
default      = "dne" # "empty" value
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "ctl-api"
kubernetes_secret_name      = "ctl-api-auth-client-secret"

user_configurable = true
