# action
name    = "admin_toggle_stratus"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name = "toggle_stratus"
inline_contents = "./src/admin/toggle-org-features.sh"

[steps.env_vars]
MODE = "enable" # or disable
ADMIN_API_URL = "http://admin.{{ .nuon.sandbox.outputs.nuon_dns.internal_domain.name }}"
