# action
name    = "temporal_restart"
timeout = "0m30s"

[[triggers]]
type           = "manual"

[[triggers]]
type           = "post-deploy-component"
component_name = "temporal"

[[steps]]
name    = "deployments_restart"
command = "./deployments-restart"

[steps.public_repo]
repo      = "nuonco/actions"
branch    = "main"
directory = "kube"

[steps.env_vars]
NAMESPACE = "temporal"
